{% set provider = "Fastly" %}
{% set version = "0.3.0" %}

{% set name = "terraform-provider-" + provider.lower() %}
{% set x4_plugin = name + '_v' + version + "_x4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/terraform-providers/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: bb47b7cb2a1276beada3019fa3ec3dd70bc1142b8d818e706b87c34d7dcfb643  # [not win]

  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  fn: {{ name }}-{{ version }}.zip  # [win]
  sha256: 40e192f0a13b6de65e6eb23a7b97cd51b1101ecaa884ee1dd308bcae118904f2  # [win64]

build:
  number: 1000
  script:
    - XCOPY {{ x4_plugin }}.exe %LIBRARY_BIN%  # [win]

requirements:
  build:
    - go 1.8.*  # [not win]
    - make  # [not win]
    - toolchain  # [not win]
  run:
    - terraform >=0.10

test:
  commands:
    - echo 'provider "{{ provider|lower }}" { version="{{ version }}" }' > init.tf  # [not win]
    - test $(terraform init | grep -c 'Downloading') = 0  # [not win]

about:
  home: https://www.terraform.io
  license: MPL 2.0
  summary: The Terraform {{ provider }} provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider|lower }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - sodre
