{% set provider = "Fastly" %}
{% set version = "0.4.0" %}

{% set name = "terraform-provider-" + provider.lower() %}
{% set x4_plugin = name + '_v' + version + "_x4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/github.com/terraform-providers/{{ name }}  # [not win]
    url: https://github.com/terraform-providers/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    fn: {{ name }}-{{ version }}.tar.gz  # [not win]
    sha256: 92926704bd0f2fabc05db85f6c3697f7cfc6951bad6bf37156a7c35cd169df60  # [not win]

    url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
    fn: {{ name }}-{{ version }}.zip  # [win]
    sha256: 8b74abce921537df95edb649403743cc3d15a2287df2a85dd76175a08cbea42a  # [win64]

build:
  number: 1000
  script:
    - XCOPY {{ x4_plugin }}.exe %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - make  # [not win]
  run:
    - terraform >=0.10

test:
  commands:
    - echo 'provider "{{ provider|lower }}" { version="{{ version }}" }' > init.tf  # [not win]
    - test $(terraform init | grep -c 'Downloading') = 0  # [not win]

about:
  home: https://www.terraform.io
  license: MPL 2.0
  summary: The Terraform {{ provider }} provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider|lower }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - sodre
