appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: tlWzBX6anNJB36LTA7rNuVNW6tLjTrag5H+xQkgcfT8ZlDumYo2Aqv242gY29iy1Vr01K/ObAIZd9sY586S2BAWHQVHu9ZlFXz/81XAhxAYv554x8Bj4y6REU0TPmSta7Ga1PWQfT9eAlMMDmYxm2iQugxqvasjXm2OMBTnIWWBkCkVmic9iKGHlqA4ggEDoc2YaDr/yxKPYNbz75Ll1hFgGlcqnogFhMpGwqTY0RuCfYpiyfO+V0f6IvYN4qdsvx6T9BhPGbU6cqZs1JJQ9CY9RMaVCroTY6XVxTC94mYRjZNeS70+h02a3nqSIWziprtCzsSEmYc4OpBZ4hnbhFYBRlhPy9ZqOHdeZZv5Az4mWVviiBzM7gv9zmYI6Bn+MaEDhlIXinOlzP2ZOnawcL//Fw2ORNGuonyQoVfWR59bgx3a+NUV7U+QcJUpbrB5UXRt1h2z+cIf+Es9521/ttY8c7nMDwYAgL52kh694DuXNfzUXJX50n2Gw6nZfQm3MWNMXJ8XWhMzF+RGGeXQ9F04rW2L28nRIhKgkDBLuvRQJY/WAoEahgBlTAXi+y2Zty4++vnyMy1/xuiXdXbQikcRYOgGE4M3eoSV91P1qeOc84ppiuKU4aZhOS5H5E8kO60w/Xe1IQkbEt4LqF6diD35rQz3azmlHBIvLYEOcp18=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
